import com.github.deminder.Day08
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test

class Day08Test {

    private val day = Day08

    private val inputString = """
        ............
        ........0...
        .....0......
        .......0....
        ....0.......
        ......A.....
        ............
        ............
        ........A...
        .........A..
        ............
        ............
    """.trimIndent();

    @Test
    fun `test solve part 1`() {
        val result = day.solve(inputString.lineSequence(), false)

        assertEquals("14", result)
    }

    @Test
    fun `test solve part 2 a`() {
        val result = day.solve(
            """
            T.........
            ...T......
            .T........
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
    """.trimIndent().lineSequence(), true
        )

        assertEquals("9", result)
    }

    @Test
    fun `test solve part 2 b`() {
        val result = day.solve(inputString.lineSequence(), true)

        assertEquals("34", result)
    }
}